# ~/.config/alacritty/alacritty.toml

[window]
opacity = 0.7
decorations = "full"
dynamic_title = true

[font]
normal = { family = "monospace", style = "Regular" }
size = 15.0

[colors.primary]
background = "0x000000"
foreground = "0xffffff"
