name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t my-docker-app .

      - name: Run tests (optional)
        run: echo "Тут можешь добавить тесты"

      # Пример пуша в Docker Hub (если хочешь)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}
      #
      # - name: Push image
      #   run: |
      #     docker tag my-docker-app mydockerhubuser/my-docker-app:latest
      #     docker push mydockerhubuser/my-docker-app:latest
